In [26]:
import numpy as np

x = list(map(int, input('Enter the values of x separated by commas: ').split(',')))
y = list(map(int, input('Enter the values of y separated by commas: ').split(',')))

A = np.array([[len(x), sum(x)],
              [sum(x), sum(np.square(x))]])
B = np.array([[sum(y)], [np.dot(x, y)]])
X = np.linalg.inv(A)@B
print(X)
print(f'The simple linear regression equation is: y =  {X[0, 0]: .3f} + {X[1, 0]: .3f}x')

Enter the values of x separated by commas:  14, 16, 18, 20, 24, 30, 32
Enter the values of y separated by commas:  52, 62, 65, 70, 76, 80, 78


[[39.66666667]
 [ 1.33333333]]
The simple linear regression equation is: y =   39.667 +  1.333x


In [29]:
from sklearn.linear_model import LinearRegression

x = np.array(list(map(int, input('Enter the values of x separated by commas: ').split(',')))).reshape(-1, 1)
y = list(map(int, input('Enter the values of y separated by commas: ').split(',')))
print(x)
model = LinearRegression().fit(x, y)
slope = model.coef_[0]
intercept = model.intercept_

equation = f"y = {slope: .2f}x + {intercept: .2f}"
print(equation)

Enter the values of x separated by commas:  1, 2, 3
Enter the values of y separated by commas:  3, 1, 2


[[1]
 [2]
 [3]]
y = -0.50x +  3.00


In [1]:
import numpy as np

x = list(map(int, input('Enter the values of x separated by commas: ').split(',')))
y = list(map(int, input('Enter the values of y separated by commas: ').split(',')))

A = np.array([[len(x), sum(x)],
             [sum(x), sum(np.square(x))]])
B = np.array([sum(y), np.dot(x, y)])
X = np.linalg.inv(A)@B.T
X

Enter the values of x separated by commas:  14, 16, 18, 20, 24, 30, 32
Enter the values of y separated by commas:  52, 62, 65, 70, 76, 80, 78


array([39.66666667,  1.33333333])

In [2]:
print(f'The simple linear regression model is: y = {X[0]:.3f} + {X[1]:.3f}x')

The simple linear regression model is: y = 39.667 + 1.333x


In [3]:
from sklearn.linear_model import LinearRegression

In [5]:
x = np.array(list(map(int, input('Enter the values of x separated by commas: ').split(',')))).reshape(-1, 1)
y = list(map(int, input('Enter the values of y separated by commas: ').split(',')))

model = LinearRegression().fit(x, y)
slope = model.coef_[0]
intercept = model.intercept_

print(f"y = {intercept: .3f} + {slope: .3f}x")

Enter the values of x separated by commas:  14, 16, 18, 20, 24, 30, 32
Enter the values of y separated by commas:  52, 62, 65, 70, 76, 80, 78


y =  39.667 +  1.333x
